### ISSUE TITLE
微软文档好像不生效

### ISSUE THREAD

**Issue by heartacker** [ladit/Userscripts#4]
1. 打开英文的网站。
没有切换按钮
![image](https://github.com/ladit/Userscripts/assets/1876302/05eb7688-94af-4f99-b439-6bb1cf30710c)

2. 手动用微软的网站的更改为中文
这个时候就有这个按钮了

3. 之后在点击转为英文， 也有按钮了
只要第一次更改之后，以后就一直都有了

**Comment by ladit** [comment]
原因是en-us页面的切换语言按钮不展示，我做了适配，可以更新一下https://greasyfork.org/zh-CN/scripts/33209-microsoftdoclanguageswitchbutton
